#!/usr/bin/env python
# coding: utf-8

# In[1]:


import requests

def fetch_all_products():
    try:
        response = requests.get("https://dummyjson.com/products?limit=100")
        data = response.json()
        print("✅ API fetch successful")
        return data.get('products', [])
    except Exception:
        print("❌ API fetch failed")
        return []



# In[2]:


def create_product_mapping(api_products):
    return {
        p['id']: {
            'title': p['title'],
            'category': p['category'],
            'brand': p['brand'],
            'rating': p['rating']
        }
        for p in api_products
    }


# In[3]:


def enrich_sales_data(transactions, product_mapping):
    enriched = []

    for t in transactions:
        pid = int(t['ProductID'][1:]) if t['ProductID'][1:].isdigit() else None
        api_data = product_mapping.get(pid)

        enriched.append({
            **t,
            'API_Category': api_data['category'] if api_data else None,
            'API_Brand': api_data['brand'] if api_data else None,
            'API_Rating': api_data['rating'] if api_data else None,
            'API_Match': True if api_data else False
        })

    return enriched


# In[4]:


def save_enriched_data(data, filename='data/enriched_sales_data.txt'):
    with open(filename, 'w') as f:
        headers = data[0].keys()
        f.write('|'.join(headers) + '\n')

        for row in data:
            f.write('|'.join(str(row[h]) for h in headers) + '\n')


# In[ ]:




